spring:
  application:
    name: book-catalog
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5431/book_catalog
    username: gustionusamba
    password: gustionusamba
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081
app:
  welcome-text: I am ready to learn Spring Boot from basic to advanced
  timezone: Asia/Jakarta
  currency: IDR
logging:
  level:
    com:
      gustionusamba:
        bookcatalog: error

---
spring:
  config:
    activate:
      on-profile: development
app:
  welcome-text: I am from development profile
  timezone: Asia/Tokyo
  currency: JPY

---
spring:
  config:
    activate:
      on-profile: staging
app:
  welcome-text: I am from staging profile
  timezone: Europe/Spain
  currency: EUR

---
spring:
  config:
    activate:
      on-profile: production
app:
  welcome-text: ${WELCOME_TEXT}
  timezone: ${TIMEZONE}
  currency: ${CURRENCY}
